# Generated by Django 5.0.14 on 2026-06-04 10:23

import memories.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="memories/",
                        validators=[memories.utils.validate_image_extension],
                    ),
                ),
                ("caption", models.CharField(max_length=300)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Screen reader description of photo",
                        max_length=200,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Memories",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(
                        default="Welcome to our memories.",
                        help_text="Displayed on the home page hero section",
                    ),
                ),
                (
                    "apology_message",
                    models.TextField(
                        default="",
                        help_text="HTML-safe apology text. <p>, <em>, <br> supported.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
