# Generated by Django 5.0.14 on 2026-06-05 05:12

import memories.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="media_type",
            field=models.CharField(
                choices=[("photo", "Photo"), ("video", "Video")],
                default="photo",
                help_text="Choose whether this memory is a photo or a video.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload a video (MP4, WebM, MOV, M4V).",
                null=True,
                upload_to="memories/videos/",
                validators=[memories.utils.validate_video_extension],
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="alt_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Screen reader description of photo/video",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a photo (JPG, PNG, GIF, WebP).",
                null=True,
                upload_to="memories/photos/",
                validators=[memories.utils.validate_image_extension],
            ),
        ),
    ]
