# Generated by Django 5.0.14 on 2026-06-05 19:37

import memories.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0002_add_video_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="BvPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Upload a photo (JPG, PNG, GIF, WebP).",
                        upload_to="bv/photos/",
                        validators=[memories.utils.validate_image_extension],
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=300)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("alt_text", models.CharField(blank=True, default="", max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "BV Photo",
                "verbose_name_plural": "BV Photos",
                "ordering": ["display_order", "date"],
            },
        ),
    ]
