# Generated by Django 5.0.14 on 2026-06-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0003_add_bv_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="alt_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Screen reader description",
                max_length=200,
            ),
        ),
    ]
