# Generated by Django 5.0.14 on 2026-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0004_add_bv_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="background_audio",
            field=models.FileField(
                blank=True,
                help_text="Background music for the home page (MP3, OGG, WAV). Plays on user interaction.",
                null=True,
                upload_to="audio/",
            ),
        ),
    ]
