# Generated by Django 5.0.14 on 2026-09-03 19:22

import memories.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0005_add_background_audio"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        default="photo",
                        help_text="Choose whether this item is a photo or a video.",
                        max_length=10,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a photo (JPG, PNG, GIF, WebP).",
                        null=True,
                        upload_to="gallery/photos/",
                        validators=[memories.utils.validate_image_extension],
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Upload a video (MP4, WebM, MOV, M4V).",
                        null=True,
                        upload_to="gallery/videos/",
                        validators=[memories.utils.validate_video_extension],
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=300)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Screen reader description",
                        max_length=200,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gallery Media",
                "verbose_name_plural": "Gallery Media",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="HomeMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        default="photo",
                        help_text="Choose whether this item is a photo or a video.",
                        max_length=10,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a photo (JPG, PNG, GIF, WebP).",
                        null=True,
                        upload_to="home/photos/",
                        validators=[memories.utils.validate_image_extension],
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Upload a video (MP4, WebM, MOV, M4V).",
                        null=True,
                        upload_to="home/videos/",
                        validators=[memories.utils.validate_video_extension],
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=300)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Screen reader description",
                        max_length=200,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Home Media",
                "verbose_name_plural": "Home Media",
                "ordering": ["display_order"],
            },
        ),
        migrations.AlterModelOptions(
            name="memory",
            options={
                "ordering": ["display_order"],
                "verbose_name": "Timeline Memory",
                "verbose_name_plural": "Timeline Memories",
            },
        ),
    ]
