# Generated by Django 5.0.14 on 2026-09-03 19:50

import memories.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0006_gallerymedia_homemedia_alter_memory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="quote_author",
            field=models.CharField(
                blank=True,
                default="Leo Christopher",
                help_text="Author name for the quote.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_text",
            field=models.CharField(
                blank=True,
                default='"You are my today and all of my tomorrows."',
                help_text="Quote displayed on the banner.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quote_video",
            field=models.FileField(
                blank=True,
                help_text="Upload a video for the Love Quote banner on the Home page (MP4, WebM, MOV).",
                null=True,
                upload_to="quote/videos/",
                validators=[memories.utils.validate_video_extension],
            ),
        ),
    ]
