"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================
# Jazzmin — Material-style Admin Theme
# ============================================================
JAZZMIN_SETTINGS = {
    # Window title
    "site_title": "Memories Admin",
    # Header brand text
    "site_header": "Memories",
    # Brand text on login page
    "site_brand": "♥ Memories",
    # Welcome text on login screen
    "welcome_sign": "Welcome back — sign in to manage your memories",
    # Copyright footer
    "copyright": "Made with ♥",
    # Search model — search memories directly from header
    "search_model": ["memories.Memory"],
    # Top menu links
    "topmenu_links": [
        {"name": "View Site", "url": "/", "new_window": True},
        {"name": "Gallery", "url": "/gallery/", "new_window": True},
        {"name": "Apology", "url": "/apology/", "new_window": True},
    ],
    # Sidebar icons
    "icons": {
        "auth":                     "fas fa-users-cog",
        "auth.user":                "fas fa-user",
        "auth.Group":               "fas fa-users",
        "memories.Memory":          "fas fa-image",
        "memories.SiteSettings":    "fas fa-cog",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    # Sidebar style
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["auth"],      # hide auth from sidebar (keep it accessible)
    "hide_models": [],
    # Related modal
    "related_modal_active": True,
    # Custom CSS / JS
    "custom_css": None,
    "custom_js":  None,
    # Use Bootstrap4 theme
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    # Change view
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "memories.memory":       "collapsible",
        "memories.sitesettings": "flat",
        "memories.bvphoto":      "flat",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    # Theme: lux gives clean Material-like light theme
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text":   False,
    "brand_small_text":  False,
    # Warm rose color scheme
    "brand_colour":          "navbar-danger",   # rose/red navbar
    "accent":                "accent-danger",
    "navbar":                "navbar-white navbar-light",
    "no_navbar_border":      False,
    "navbar_fixed":          True,
    "layout_boxed":          False,
    "footer_fixed":          False,
    "sidebar_fixed":         True,
    "sidebar":               "sidebar-light-danger",   # light sidebar, rose active
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style":  False,
    "sidebar_nav_flat_style":    False,
    "theme":                 "minty",   # minty = clean light Material-like
    "dark_mode_theme":       None,
    "button_classes": {
        "primary":   "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
}



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-=#(s-o(ejm5x41a2im!f&bnks12^7swa8_6f*mg673jdqf_9za',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = [
    "love-moments-jfag.onrender.com",
    "127.0.0.1",
    "localhost",
]

# Application definition

INSTALLED_APPS = [
    "jazzmin",                          # must be before django.contrib.admin
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Project apps
    "memories",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "memories.context_processors.site_audio",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": config(
        'DATABASE_URL',
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        cast=dj_database_url.parse,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (user-uploaded content)
MEDIA_URL = 'media/'
MEDIA_ROOT = Path('C:/website_media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
